/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import com.namnv.movieapp.data.models.MovieDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param genres 
 * @param id 
 * @param movies 
 */
@JsonClass(generateAdapter = true)

data class GenresDTO (

    @Json(name = "genres")
    var genres: kotlin.String? = null,

    @Json(name = "id")
    var id: kotlin.Long? = null,

    @Json(name = "movies")
    var movies: kotlin.collections.MutableSet<MovieDTO>? = null

)

