/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import com.namnv.movieapp.data.models.GenresDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param originName 
 * @param isCompleted 
 * @param slug 
 * @param episodeCurrent 
 * @param episodeTotal 
 * @param quality 
 * @param year 
 * @param isSingle 
 * @param premiumOnly 
 * @param id 
 * @param trailerUrl 
 * @param time 
 * @param content 
 * @param thumbUrl 
 * @param posterUrl 
 * @param actors 
 * @param country 
 * @param genres 
 */
@JsonClass(generateAdapter = true)

data class MovieDTO (

    @Json(name = "name")
    var name: kotlin.String?,

    @Json(name = "originName")
    var originName: kotlin.String?,

    @Json(name = "isCompleted")
    var isCompleted: kotlin.Boolean?,

    @Json(name = "slug")
    var slug: kotlin.String?,

    @Json(name = "episodeCurrent")
    var episodeCurrent: kotlin.String?,

    @Json(name = "episodeTotal")
    var episodeTotal: kotlin.Int?,

    @Json(name = "quality")
    var quality: kotlin.String?,

    @Json(name = "year")
    var year: kotlin.Int?,

    @Json(name = "isSingle")
    var isSingle: kotlin.Boolean?,

    @Json(name = "premiumOnly")
    var premiumOnly: kotlin.Boolean?,

    @Json(name = "id")
    var id: kotlin.Long? = null,

    @Json(name = "trailerUrl")
    var trailerUrl: kotlin.String? = null,

    @Json(name = "time")
    var time: kotlin.String? = null,

    @Json(name = "content")
    var content: kotlin.String? = null,

    @Json(name = "thumbUrl")
    var thumbUrl: kotlin.String? = null,

    @Json(name = "posterUrl")
    var posterUrl: kotlin.String? = null,

    @Json(name = "actors")
    var actors: kotlin.String? = null,

    @Json(name = "country")
    var country: kotlin.String? = null,

    @Json(name = "genres")
    var genres: kotlin.collections.MutableSet<GenresDTO>? = null

)

