/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import com.namnv.movieapp.data.models.MovieDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param part 
 * @param linkEmbed 
 * @param linkM3u8 
 * @param id 
 * @param movie 
 */
@JsonClass(generateAdapter = true)

data class MovieResourceDTO (

    @Json(name = "part")
    var part: kotlin.Int,

    @Json(name = "linkEmbed")
    var linkEmbed: kotlin.String,

    @Json(name = "linkM3u8")
    var linkM3u8: kotlin.String,

    @Json(name = "id")
    var id: kotlin.Long? = null,

    @Json(name = "movie")
    var movie: MovieDTO? = null

)

