/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param username 
 * @param password 
 * @param rememberMe 
 */
@JsonClass(generateAdapter = true)

data class LoginVM (

    @Json(name = "username")
    var username: kotlin.String,

    @Json(name = "password")
    var password: kotlin.String,

    @Json(name = "rememberMe")
    var rememberMe: kotlin.Boolean? = null

)

