/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import com.namnv.movieapp.data.models.GenresDTO
import com.namnv.movieapp.data.models.MovieDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param movie 
 * @param genres 
 */
@JsonClass(generateAdapter = true)

data class MovieGenresDTO (

    @Json(name = "id")
    var id: kotlin.Long? = null,

    @Json(name = "movie")
    var movie: MovieDTO? = null,

    @Json(name = "genres")
    var genres: GenresDTO? = null

)

