/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currentPassword 
 * @param newPassword 
 */
@JsonClass(generateAdapter = true)

data class PasswordChangeDTO (

    @Json(name = "currentPassword")
    var currentPassword: kotlin.String? = null,

    @Json(name = "newPassword")
    var newPassword: kotlin.String? = null

)

