/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import com.namnv.movieapp.data.models.UserDTO

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param paymentTime 
 * @param paymentPrice 
 * @param paymentMethod 
 * @param status 
 * @param transactionId 
 * @param id 
 * @param user 
 */
@JsonClass(generateAdapter = true)

data class PaymentDTO (

    @Json(name = "paymentTime")
    var paymentTime: kotlin.Long,

    @Json(name = "paymentPrice")
    var paymentPrice: kotlin.Long,

    @Json(name = "paymentMethod")
    var paymentMethod: kotlin.String,

    @Json(name = "status")
    var status: kotlin.String,

    @Json(name = "transactionId")
    var transactionId: kotlin.String,

    @Json(name = "id")
    var id: kotlin.Long? = null,

    @Json(name = "user")
    var user: UserDTO? = null

)

