/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.apis.AuthorityResourceApi
import com.namnv.movieapp.data.models.Authority

class AuthorityResourceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthorityResourceApi
        //val apiInstance = AuthorityResourceApi()

        // to test createAuthority
        should("test createAuthority") {
            // uncomment below to test createAuthority
            //val authority : Authority =  // Authority | 
            //val result : Authority = apiInstance.createAuthority(authority)
            //result shouldBe ("TODO")
        }

        // to test deleteAuthority
        should("test deleteAuthority") {
            // uncomment below to test deleteAuthority
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.deleteAuthority(id)
        }

        // to test getAllAuthorities
        should("test getAllAuthorities") {
            // uncomment below to test getAllAuthorities
            //val result : kotlin.collections.MutableList<Authority> = apiInstance.getAllAuthorities()
            //result shouldBe ("TODO")
        }

        // to test getAuthority
        should("test getAuthority") {
            // uncomment below to test getAuthority
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : Authority = apiInstance.getAuthority(id)
            //result shouldBe ("TODO")
        }

    }
}
