/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.apis.AuthenticateControllerApi
import com.namnv.movieapp.data.models.JWTToken
import com.namnv.movieapp.data.models.LoginVM

class AuthenticateControllerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthenticateControllerApi
        //val apiInstance = AuthenticateControllerApi()

        // to test authorize
        should("test authorize") {
            // uncomment below to test authorize
            //val loginVM : LoginVM =  // LoginVM | 
            //val result : JWTToken = apiInstance.authorize(loginVM)
            //result shouldBe ("TODO")
        }

        // to test isAuthenticated
        should("test isAuthenticated") {
            // uncomment below to test isAuthenticated
            //val result : kotlin.String = apiInstance.isAuthenticated()
            //result shouldBe ("TODO")
        }

    }
}
