/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.apis.GenresResourceApi
import com.namnv.movieapp.data.models.GenresDTO

class GenresResourceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GenresResourceApi
        //val apiInstance = GenresResourceApi()

        // to test createGenres
        should("test createGenres") {
            // uncomment below to test createGenres
            //val genresDTO : GenresDTO =  // GenresDTO | 
            //val result : GenresDTO = apiInstance.createGenres(genresDTO)
            //result shouldBe ("TODO")
        }

        // to test deleteGenres
        should("test deleteGenres") {
            // uncomment below to test deleteGenres
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //apiInstance.deleteGenres(id)
        }

        // to test getAllGenres
        should("test getAllGenres") {
            // uncomment below to test getAllGenres
            //val page : kotlin.Int = 56 // kotlin.Int | Zero-based page index (0..N)
            //val size : kotlin.Int = 56 // kotlin.Int | The size of the page to be returned
            //val sort : kotlin.collections.MutableList<kotlin.String> =  // kotlin.collections.MutableList<kotlin.String> | Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
            //val result : kotlin.collections.MutableList<GenresDTO> = apiInstance.getAllGenres(page, size, sort)
            //result shouldBe ("TODO")
        }

        // to test getGenres
        should("test getGenres") {
            // uncomment below to test getGenres
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : GenresDTO = apiInstance.getGenres(id)
            //result shouldBe ("TODO")
        }

        // to test partialUpdateGenres
        should("test partialUpdateGenres") {
            // uncomment below to test partialUpdateGenres
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val genresDTO : GenresDTO =  // GenresDTO | 
            //val result : GenresDTO = apiInstance.partialUpdateGenres(id, genresDTO)
            //result shouldBe ("TODO")
        }

        // to test updateGenres
        should("test updateGenres") {
            // uncomment below to test updateGenres
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val genresDTO : GenresDTO =  // GenresDTO | 
            //val result : GenresDTO = apiInstance.updateGenres(id, genresDTO)
            //result shouldBe ("TODO")
        }

    }
}
