/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.apis.HistoryResourceApi
import com.namnv.movieapp.data.models.HistoryDTO

class HistoryResourceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HistoryResourceApi
        //val apiInstance = HistoryResourceApi()

        // to test createHistory
        should("test createHistory") {
            // uncomment below to test createHistory
            //val historyDTO : HistoryDTO =  // HistoryDTO | 
            //val result : HistoryDTO = apiInstance.createHistory(historyDTO)
            //result shouldBe ("TODO")
        }

        // to test deleteHistory
        should("test deleteHistory") {
            // uncomment below to test deleteHistory
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //apiInstance.deleteHistory(id)
        }

        // to test getAllHistories
        should("test getAllHistories") {
            // uncomment below to test getAllHistories
            //val page : kotlin.Int = 56 // kotlin.Int | Zero-based page index (0..N)
            //val size : kotlin.Int = 56 // kotlin.Int | The size of the page to be returned
            //val sort : kotlin.collections.MutableList<kotlin.String> =  // kotlin.collections.MutableList<kotlin.String> | Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
            //val result : kotlin.collections.MutableList<HistoryDTO> = apiInstance.getAllHistories(page, size, sort)
            //result shouldBe ("TODO")
        }

        // to test getHistory
        should("test getHistory") {
            // uncomment below to test getHistory
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : HistoryDTO = apiInstance.getHistory(id)
            //result shouldBe ("TODO")
        }

        // to test partialUpdateHistory
        should("test partialUpdateHistory") {
            // uncomment below to test partialUpdateHistory
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val historyDTO : HistoryDTO =  // HistoryDTO | 
            //val result : HistoryDTO = apiInstance.partialUpdateHistory(id, historyDTO)
            //result shouldBe ("TODO")
        }

        // to test updateHistory
        should("test updateHistory") {
            // uncomment below to test updateHistory
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val historyDTO : HistoryDTO =  // HistoryDTO | 
            //val result : HistoryDTO = apiInstance.updateHistory(id, historyDTO)
            //result shouldBe ("TODO")
        }

    }
}
