/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.apis.MovieGenresResourceApi
import com.namnv.movieapp.data.models.MovieGenresDTO

class MovieGenresResourceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MovieGenresResourceApi
        //val apiInstance = MovieGenresResourceApi()

        // to test createMovieGenres
        should("test createMovieGenres") {
            // uncomment below to test createMovieGenres
            //val movieGenresDTO : MovieGenresDTO =  // MovieGenresDTO | 
            //val result : MovieGenresDTO = apiInstance.createMovieGenres(movieGenresDTO)
            //result shouldBe ("TODO")
        }

        // to test deleteMovieGenres
        should("test deleteMovieGenres") {
            // uncomment below to test deleteMovieGenres
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //apiInstance.deleteMovieGenres(id)
        }

        // to test getAllMovieGenres
        should("test getAllMovieGenres") {
            // uncomment below to test getAllMovieGenres
            //val page : kotlin.Int = 56 // kotlin.Int | Zero-based page index (0..N)
            //val size : kotlin.Int = 56 // kotlin.Int | The size of the page to be returned
            //val sort : kotlin.collections.MutableList<kotlin.String> =  // kotlin.collections.MutableList<kotlin.String> | Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
            //val result : kotlin.collections.MutableList<MovieGenresDTO> = apiInstance.getAllMovieGenres(page, size, sort)
            //result shouldBe ("TODO")
        }

        // to test getMovieGenres
        should("test getMovieGenres") {
            // uncomment below to test getMovieGenres
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : MovieGenresDTO = apiInstance.getMovieGenres(id)
            //result shouldBe ("TODO")
        }

        // to test partialUpdateMovieGenres
        should("test partialUpdateMovieGenres") {
            // uncomment below to test partialUpdateMovieGenres
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val movieGenresDTO : MovieGenresDTO =  // MovieGenresDTO | 
            //val result : MovieGenresDTO = apiInstance.partialUpdateMovieGenres(id, movieGenresDTO)
            //result shouldBe ("TODO")
        }

        // to test updateMovieGenres
        should("test updateMovieGenres") {
            // uncomment below to test updateMovieGenres
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val movieGenresDTO : MovieGenresDTO =  // MovieGenresDTO | 
            //val result : MovieGenresDTO = apiInstance.updateMovieGenres(id, movieGenresDTO)
            //result shouldBe ("TODO")
        }

    }
}
