/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.apis.PaymentResourceApi
import com.namnv.movieapp.data.models.PaymentDTO

class PaymentResourceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentResourceApi
        //val apiInstance = PaymentResourceApi()

        // to test createPayment
        should("test createPayment") {
            // uncomment below to test createPayment
            //val paymentDTO : PaymentDTO =  // PaymentDTO | 
            //val result : PaymentDTO = apiInstance.createPayment(paymentDTO)
            //result shouldBe ("TODO")
        }

        // to test deletePayment
        should("test deletePayment") {
            // uncomment below to test deletePayment
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //apiInstance.deletePayment(id)
        }

        // to test getAllPayments
        should("test getAllPayments") {
            // uncomment below to test getAllPayments
            //val page : kotlin.Int = 56 // kotlin.Int | Zero-based page index (0..N)
            //val size : kotlin.Int = 56 // kotlin.Int | The size of the page to be returned
            //val sort : kotlin.collections.MutableList<kotlin.String> =  // kotlin.collections.MutableList<kotlin.String> | Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
            //val result : kotlin.collections.MutableList<PaymentDTO> = apiInstance.getAllPayments(page, size, sort)
            //result shouldBe ("TODO")
        }

        // to test getPayment
        should("test getPayment") {
            // uncomment below to test getPayment
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : PaymentDTO = apiInstance.getPayment(id)
            //result shouldBe ("TODO")
        }

        // to test partialUpdatePayment
        should("test partialUpdatePayment") {
            // uncomment below to test partialUpdatePayment
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val paymentDTO : PaymentDTO =  // PaymentDTO | 
            //val result : PaymentDTO = apiInstance.partialUpdatePayment(id, paymentDTO)
            //result shouldBe ("TODO")
        }

        // to test updatePayment
        should("test updatePayment") {
            // uncomment below to test updatePayment
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val paymentDTO : PaymentDTO =  // PaymentDTO | 
            //val result : PaymentDTO = apiInstance.updatePayment(id, paymentDTO)
            //result shouldBe ("TODO")
        }

    }
}
