/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.apis.PlaylistResourceApi
import com.namnv.movieapp.data.models.PlaylistDTO

class PlaylistResourceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlaylistResourceApi
        //val apiInstance = PlaylistResourceApi()

        // to test createPlaylist
        should("test createPlaylist") {
            // uncomment below to test createPlaylist
            //val playlistDTO : PlaylistDTO =  // PlaylistDTO | 
            //val result : PlaylistDTO = apiInstance.createPlaylist(playlistDTO)
            //result shouldBe ("TODO")
        }

        // to test deletePlaylist
        should("test deletePlaylist") {
            // uncomment below to test deletePlaylist
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //apiInstance.deletePlaylist(id)
        }

        // to test getAllPlaylists
        should("test getAllPlaylists") {
            // uncomment below to test getAllPlaylists
            //val page : kotlin.Int = 56 // kotlin.Int | Zero-based page index (0..N)
            //val size : kotlin.Int = 56 // kotlin.Int | The size of the page to be returned
            //val sort : kotlin.collections.MutableList<kotlin.String> =  // kotlin.collections.MutableList<kotlin.String> | Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
            //val result : kotlin.collections.MutableList<PlaylistDTO> = apiInstance.getAllPlaylists(page, size, sort)
            //result shouldBe ("TODO")
        }

        // to test getPlaylist
        should("test getPlaylist") {
            // uncomment below to test getPlaylist
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : PlaylistDTO = apiInstance.getPlaylist(id)
            //result shouldBe ("TODO")
        }

        // to test partialUpdatePlaylist
        should("test partialUpdatePlaylist") {
            // uncomment below to test partialUpdatePlaylist
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val playlistDTO : PlaylistDTO =  // PlaylistDTO | 
            //val result : PlaylistDTO = apiInstance.partialUpdatePlaylist(id, playlistDTO)
            //result shouldBe ("TODO")
        }

        // to test updatePlaylist
        should("test updatePlaylist") {
            // uncomment below to test updatePlaylist
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val playlistDTO : PlaylistDTO =  // PlaylistDTO | 
            //val result : PlaylistDTO = apiInstance.updatePlaylist(id, playlistDTO)
            //result shouldBe ("TODO")
        }

    }
}
