/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.apis.PremiumResourceApi
import com.namnv.movieapp.data.models.PremiumDTO

class PremiumResourceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PremiumResourceApi
        //val apiInstance = PremiumResourceApi()

        // to test createPremium
        should("test createPremium") {
            // uncomment below to test createPremium
            //val premiumDTO : PremiumDTO =  // PremiumDTO | 
            //val result : PremiumDTO = apiInstance.createPremium(premiumDTO)
            //result shouldBe ("TODO")
        }

        // to test deletePremium
        should("test deletePremium") {
            // uncomment below to test deletePremium
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //apiInstance.deletePremium(id)
        }

        // to test getAllPremiums
        should("test getAllPremiums") {
            // uncomment below to test getAllPremiums
            //val page : kotlin.Int = 56 // kotlin.Int | Zero-based page index (0..N)
            //val size : kotlin.Int = 56 // kotlin.Int | The size of the page to be returned
            //val sort : kotlin.collections.MutableList<kotlin.String> =  // kotlin.collections.MutableList<kotlin.String> | Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
            //val result : kotlin.collections.MutableList<PremiumDTO> = apiInstance.getAllPremiums(page, size, sort)
            //result shouldBe ("TODO")
        }

        // to test getPremium
        should("test getPremium") {
            // uncomment below to test getPremium
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : PremiumDTO = apiInstance.getPremium(id)
            //result shouldBe ("TODO")
        }

        // to test partialUpdatePremium
        should("test partialUpdatePremium") {
            // uncomment below to test partialUpdatePremium
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val premiumDTO : PremiumDTO =  // PremiumDTO | 
            //val result : PremiumDTO = apiInstance.partialUpdatePremium(id, premiumDTO)
            //result shouldBe ("TODO")
        }

        // to test updatePremium
        should("test updatePremium") {
            // uncomment below to test updatePremium
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val premiumDTO : PremiumDTO =  // PremiumDTO | 
            //val result : PremiumDTO = apiInstance.updatePremium(id, premiumDTO)
            //result shouldBe ("TODO")
        }

    }
}
