/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.apis.PublicUserResourceApi
import com.namnv.movieapp.data.models.UserDTO

class PublicUserResourceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PublicUserResourceApi
        //val apiInstance = PublicUserResourceApi()

        // to test getAllPublicUsers
        should("test getAllPublicUsers") {
            // uncomment below to test getAllPublicUsers
            //val page : kotlin.Int = 56 // kotlin.Int | Zero-based page index (0..N)
            //val size : kotlin.Int = 56 // kotlin.Int | The size of the page to be returned
            //val sort : kotlin.collections.MutableList<kotlin.String> =  // kotlin.collections.MutableList<kotlin.String> | Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
            //val result : kotlin.collections.MutableList<UserDTO> = apiInstance.getAllPublicUsers(page, size, sort)
            //result shouldBe ("TODO")
        }

    }
}
