/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.models.HistoryDTO
import com.namnv.movieapp.data.models.MovieDTO
import com.namnv.movieapp.data.models.UserDTO

class HistoryDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HistoryDTO
        //val modelInstance = HistoryDTO()

        // to test the property `part`
        should("test part") {
            // uncomment below to test the property
            //modelInstance.part shouldBe ("TODO")
        }

        // to test the property `stopTime`
        should("test stopTime") {
            // uncomment below to test the property
            //modelInstance.stopTime shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `movie`
        should("test movie") {
            // uncomment below to test the property
            //modelInstance.movie shouldBe ("TODO")
        }

    }
}
