/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.models.JWTToken

class JWTTokenTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JWTToken
        //val modelInstance = JWTToken()

        // to test the property `idToken`
        should("test idToken") {
            // uncomment below to test the property
            //modelInstance.idToken shouldBe ("TODO")
        }

    }
}
