/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.models.KeyAndPasswordVM

class KeyAndPasswordVMTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of KeyAndPasswordVM
        //val modelInstance = KeyAndPasswordVM()

        // to test the property `key`
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `newPassword`
        should("test newPassword") {
            // uncomment below to test the property
            //modelInstance.newPassword shouldBe ("TODO")
        }

    }
}
