/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.models.ManagedUserVM

class ManagedUserVMTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ManagedUserVM
        //val modelInstance = ManagedUserVM()

        // to test the property `login`
        should("test login") {
            // uncomment below to test the property
            //modelInstance.login shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `firstName`
        should("test firstName") {
            // uncomment below to test the property
            //modelInstance.firstName shouldBe ("TODO")
        }

        // to test the property `lastName`
        should("test lastName") {
            // uncomment below to test the property
            //modelInstance.lastName shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `imageUrl`
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `activated`
        should("test activated") {
            // uncomment below to test the property
            //modelInstance.activated shouldBe ("TODO")
        }

        // to test the property `langKey`
        should("test langKey") {
            // uncomment below to test the property
            //modelInstance.langKey shouldBe ("TODO")
        }

        // to test the property `createdBy`
        should("test createdBy") {
            // uncomment below to test the property
            //modelInstance.createdBy shouldBe ("TODO")
        }

        // to test the property `createdDate`
        should("test createdDate") {
            // uncomment below to test the property
            //modelInstance.createdDate shouldBe ("TODO")
        }

        // to test the property `lastModifiedBy`
        should("test lastModifiedBy") {
            // uncomment below to test the property
            //modelInstance.lastModifiedBy shouldBe ("TODO")
        }

        // to test the property `lastModifiedDate`
        should("test lastModifiedDate") {
            // uncomment below to test the property
            //modelInstance.lastModifiedDate shouldBe ("TODO")
        }

        // to test the property `authorities`
        should("test authorities") {
            // uncomment below to test the property
            //modelInstance.authorities shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

    }
}
