/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.models.MovieResourceDTO
import com.namnv.movieapp.data.models.MovieDTO

class MovieResourceDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MovieResourceDTO
        //val modelInstance = MovieResourceDTO()

        // to test the property `part`
        should("test part") {
            // uncomment below to test the property
            //modelInstance.part shouldBe ("TODO")
        }

        // to test the property `linkEmbed`
        should("test linkEmbed") {
            // uncomment below to test the property
            //modelInstance.linkEmbed shouldBe ("TODO")
        }

        // to test the property `linkM3u8`
        should("test linkM3u8") {
            // uncomment below to test the property
            //modelInstance.linkM3u8 shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `movie`
        should("test movie") {
            // uncomment below to test the property
            //modelInstance.movie shouldBe ("TODO")
        }

    }
}
