/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.models.MovieGenresDTO
import com.namnv.movieapp.data.models.GenresDTO
import com.namnv.movieapp.data.models.MovieDTO

class MovieGenresDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MovieGenresDTO
        //val modelInstance = MovieGenresDTO()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `movie`
        should("test movie") {
            // uncomment below to test the property
            //modelInstance.movie shouldBe ("TODO")
        }

        // to test the property `genres`
        should("test genres") {
            // uncomment below to test the property
            //modelInstance.genres shouldBe ("TODO")
        }

    }
}
