/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.models.MovieDTO
import com.namnv.movieapp.data.models.GenresDTO

class MovieDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MovieDTO
        //val modelInstance = MovieDTO()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `originName`
        should("test originName") {
            // uncomment below to test the property
            //modelInstance.originName shouldBe ("TODO")
        }

        // to test the property `isCompleted`
        should("test isCompleted") {
            // uncomment below to test the property
            //modelInstance.isCompleted shouldBe ("TODO")
        }

        // to test the property `slug`
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `episodeCurrent`
        should("test episodeCurrent") {
            // uncomment below to test the property
            //modelInstance.episodeCurrent shouldBe ("TODO")
        }

        // to test the property `episodeTotal`
        should("test episodeTotal") {
            // uncomment below to test the property
            //modelInstance.episodeTotal shouldBe ("TODO")
        }

        // to test the property `quality`
        should("test quality") {
            // uncomment below to test the property
            //modelInstance.quality shouldBe ("TODO")
        }

        // to test the property `year`
        should("test year") {
            // uncomment below to test the property
            //modelInstance.year shouldBe ("TODO")
        }

        // to test the property `isSingle`
        should("test isSingle") {
            // uncomment below to test the property
            //modelInstance.isSingle shouldBe ("TODO")
        }

        // to test the property `premiumOnly`
        should("test premiumOnly") {
            // uncomment below to test the property
            //modelInstance.premiumOnly shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `trailerUrl`
        should("test trailerUrl") {
            // uncomment below to test the property
            //modelInstance.trailerUrl shouldBe ("TODO")
        }

        // to test the property `time`
        should("test time") {
            // uncomment below to test the property
            //modelInstance.time shouldBe ("TODO")
        }

        // to test the property `content`
        should("test content") {
            // uncomment below to test the property
            //modelInstance.content shouldBe ("TODO")
        }

        // to test the property `thumbUrl`
        should("test thumbUrl") {
            // uncomment below to test the property
            //modelInstance.thumbUrl shouldBe ("TODO")
        }

        // to test the property `posterUrl`
        should("test posterUrl") {
            // uncomment below to test the property
            //modelInstance.posterUrl shouldBe ("TODO")
        }

        // to test the property `actors`
        should("test actors") {
            // uncomment below to test the property
            //modelInstance.actors shouldBe ("TODO")
        }

        // to test the property `country`
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `genres`
        should("test genres") {
            // uncomment below to test the property
            //modelInstance.genres shouldBe ("TODO")
        }

    }
}
