/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.namnv.movieapp.data.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.namnv.movieapp.data.models.PaymentDTO
import com.namnv.movieapp.data.models.UserDTO

class PaymentDTOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentDTO
        //val modelInstance = PaymentDTO()

        // to test the property `paymentTime`
        should("test paymentTime") {
            // uncomment below to test the property
            //modelInstance.paymentTime shouldBe ("TODO")
        }

        // to test the property `paymentPrice`
        should("test paymentPrice") {
            // uncomment below to test the property
            //modelInstance.paymentPrice shouldBe ("TODO")
        }

        // to test the property `paymentMethod`
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `transactionId`
        should("test transactionId") {
            // uncomment below to test the property
            //modelInstance.transactionId shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

    }
}
